apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: {{ .Values.hospital.namespace }}
spec:
  type: {{ .Values.svc.type }} 
  ports:
    - port: {{ .Values.svc.port }}
      targetPort: {{ .Values.svc.targetPort }}
      protocol: {{ .Values.svc.protocol }}
  selector:
    app: {{ .Values.svc.app }}